
namespace MachineSimulator.UVCCamera
{
    public static class OpenCVConstants
    {
        public enum VideoCaptureProperties
        {
            CAP_PROP_POS_MSEC = 0,
            CAP_PROP_POS_FRAMES = 1,
            CAP_PROP_POS_AVI_RATIO = 2,
            CAP_PROP_FRAME_WIDTH = 3,
            CAP_PROP_FRAME_HEIGHT = 4,
            CAP_PROP_FPS = 5,
            CAP_PROP_FOURCC = 6,
            CAP_PROP_FRAME_COUNT = 7,
            CAP_PROP_FORMAT = 8,
            CAP_PROP_MODE = 9,
            CAP_PROP_BRIGHTNESS = 10,
            CAP_PROP_CONTRAST = 11,
            CAP_PROP_SATURATION = 12,
            CAP_PROP_HUE = 13,
            CAP_PROP_GAIN = 14,
            CAP_PROP_EXPOSURE = 15,
            CAP_PROP_CONVERT_RGB = 16,
            CAP_PROP_WHITE_BALANCE_BLUE_U = 17,
            CAP_PROP_RECTIFICATION = 18,
            CAP_PROP_MONOCHROME = 19,
            CAP_PROP_SHARPNESS = 20,
            CAP_PROP_AUTO_EXPOSURE = 21,
            CAP_PROP_GAMMA = 22,
            CAP_PROP_TEMPERATURE = 23,
            CAP_PROP_TRIGGER = 24,
            CAP_PROP_TRIGGER_DELAY = 25,
            CAP_PROP_WHITE_BALANCE_RED_V = 26,
            CAP_PROP_ZOOM = 27,
            CAP_PROP_FOCUS = 28,
            CAP_PROP_GUID = 29,
            CAP_PROP_ISO_SPEED = 30,
            CAP_PROP_MAX_DC1394 = 31,
            CAP_PROP_BACKLIGHT = 32,
            CAP_PROP_PAN = 33,
            CAP_PROP_TILT = 34,
            CAP_PROP_ROLL = 35,
            CAP_PROP_IRIS = 36,
            CAP_PROP_SETTINGS = 37,
            CAP_PROP_BUFFERSIZE = 38,
            CAP_PROP_AUTOFOCUS = 39,
            CAP_PROP_SAR_NUM = 40,
            CAP_PROP_SAR_DEN = 41,
            CAP_PROP_BACKEND = 42,
            CAP_PROP_CHANNEL = 43,
            CAP_PROP_AUTO_WB = 44,
            CAP_PROP_WB_TEMPERATURE = 45,
            CAP_PROP_CODEC_PIXEL_FORMAT = 46,
            CAP_PROP_BITRATE = 47,
            CAP_PROP_ORIENTATION_META = 48,
            CAP_PROP_ORIENTATION_AUTO = 49,
            CAP_PROP_HW_ACCELERATION = 50,
            CAP_PROP_HW_DEVICE = 51,
            CAP_PROP_HW_ACCELERATION_USE_OPENCL = 52,
            CAP_PROP_OPEN_TIMEOUT_MSEC = 53,
            CAP_PROP_READ_TIMEOUT_MSEC = 54,
            CAP_PROP_STREAM_OPEN_TIME_USEC = 55,
            CAP_PROP_VIDEO_TOTAL_CHANNELS = 56,
            CAP_PROP_VIDEO_STREAM = 57,
            CAP_PROP_AUDIO_STREAM = 58,
            CAP_PROP_AUDIO_POS = 59,
            CAP_PROP_AUDIO_SHIFT_NSEC = 60,
            CAP_PROP_AUDIO_DATA_DEPTH = 61,
            CAP_PROP_AUDIO_SAMPLES_PER_SECOND = 62,
            CAP_PROP_AUDIO_BASE_INDEX = 63,
            CAP_PROP_AUDIO_TOTAL_CHANNELS = 64,
            CAP_PROP_AUDIO_TOTAL_STREAMS = 65,
            CAP_PROP_AUDIO_SYNCHRONIZE = 66,
            CAP_PROP_LRF_HAS_KEY_FRAME = 67,
            CAP_PROP_CODEC_EXTRADATA_INDEX = 68,
            CAP_PROP_FRAME_TYPE = 69,
            CAP_PROP_N_THREADS = 70
        }
    }
}
